name: Run Checks

on:
  pull_request:
  push:
    branches:
      - main

env:
  APTOS_DEVNET_API_KEY: ${{ secrets.APTOS_DEVNET_API_KEY }}
  APTOS_TESTNET_API_KEY: ${{ secrets.APTOS_TESTNET_API_KEY }}
  APTOS_MAINNET_API_KEY: ${{ secrets.APTOS_MAINNET_API_KEY }}

jobs:
  run-all-checks:
    name: Run All Checks
    runs-on: ubuntu-latest-16-core
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Install Dependencies
        run: pnpm i

      - name: Run Checks
        run: pnpm check
